services:
  db:
    image: postgres:16-alpine
    container_name: contabilidade_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-contabilidade}
      POSTGRES_USER: ${POSTGRES_USER:-conta}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-conta}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer:4
    container_name: contabilidade_adminer
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8081:8080"

volumes:
  db-data:
